example:
  common:
    default: anyDefault
    defaultAll: anyDefault
  development
    default: anyDefault
    defaultAll: anyDefault
  test
    default: anyDefault
    defaultAll: anyDefault
  production
    default: anyDefault
    defaultAll: anyDefault
